server {
    listen 80;
    server_name draw.raynathus.com.br;

    client_max_body_size 25m;

    location / {
        proxy_pass http://127.0.0.1:8050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
